### ISSUE TITLE
PXD-2196 ⁃ Fence returns 500 when hit refresh token endpoint

### ISSUE THREAD

**Issue by philloooo** [uc-cdis/fence#463]
Wed Oct 24 04:28:00.494236 2018] [wsgi:error] [pid 1420:tid 140208161601280] [2018-10-24 04:28:00,494][ fence][ ERROR] Catch exception
[Wed Oct 24 04:28:00.494263 2018] [wsgi:error] [pid 1420:tid 140208161601280] Traceback (most recent call last):
[Wed Oct 24 04:28:00.494266 2018] [wsgi:error] [pid 1420:tid 140208161601280] File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
[Wed Oct 24 04:28:00.494268 2018] [wsgi:error] [pid 1420:tid 140208161601280] rv = self.dispatch_request()
[Wed Oct 24 04:28:00.494270 2018] [wsgi:error] [pid 1420:tid 140208161601280] File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
[Wed Oct 24 04:28:00.494273 2018] [wsgi:error] [pid 1420:tid 140208161601280] return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 24 04:28:00.494275 2018] [wsgi:error] [pid 1420:tid 140208161601280] File "/fence/fence/blueprints/oauth2.py", line 281, in get_token
[Wed Oct 24 04:28:00.494277 2018] [wsgi:error] [pid 1420:tid 140208161601280] return server.create_token_response()
[Wed Oct 24 04:28:00.494280 2018] [wsgi:error] [pid 1420:tid 140208161601280] File "/usr/local/lib/python2.7/dist-packages/authlib/flask/oauth2/authorization_server.py", line 253, in create_token_response
[Wed Oct 24 04:28:00.494282 2018] [wsgi:error] [pid 1420:tid 140208161601280] AuthorizationServer, self).create_token_response(req)
[Wed Oct 24 04:28:00.494284 2018] [wsgi:error] [pid 1420:tid 140208161601280] File "/usr/local/lib/python2.7/dist-packages/authlib/specs/rfc6749/authorization_server.py", line 166, in create_token_response
[Wed Oct 24 04:28:00.494286 2018] [wsgi:error] [pid 1420:tid 140208161601280] grant.validate_token_request()
[Wed Oct 24 04:28:00.494288 2018] [wsgi:error] [pid 1420:tid 140208161601280] File "/fence/fence/oidc/grants/refresh_token_grant.py", line 81, in validate_token_request
[Wed Oct 24 04:28:00.494290 2018] [wsgi:error] [pid 1420:tid 140208161601280] self._validate_token_scope(token)
[Wed Oct 24 04:28:00.494292 2018] [wsgi:error] [pid 1420:tid 140208161601280] File "/usr/local/lib/python2.7/dist-packages/authlib/specs/rfc6749/grants/refresh_token.py", line 66, in _validate_token_scope
[Wed Oct 24 04:28:00.494293 2018] [wsgi:error] [pid 1420:tid 140208161601280] original_scope = token.get_scope()
[Wed Oct 24 04:28:00.494295 2018] [wsgi:error] [pid 1420:tid 140208161601280] AttributeError: 'dict' object has no attribute 'get_scope'
[Wed Oct 24 04:28:00.494524 2018] [wsgi:error] [pid 1420:tid 140208161601280] [2018-10-24 04:28:00,494][ fence][ ERROR] 500 HTTP error occured. ID: 3d6a26a7-5eee-4fa0-a6ef-ed791c30290dtea

**Comment by philloooo** [comment]
➤ giangbui commented:

Remember to un-comment the integration test for refresh token after this story is resolved
